import { parrotInformation } from "@/constant/parrot";
import Head from "next/head";
import React from "react";
import { useEffect } from "react";
import { useState } from "react";

const Gallery = () => {
  const [filterinput, setFilterinput] = useState();
  const [newParrot, setnewParrot] = useState();

  // useEffect(() => {
  //   const Parrot = parrotInformation.find((parrot) => {
  //     return parrot.id = filterinput;
  //   });
  //   console.log(Parrot);
  //   setnewParrot(Parrot);
  // }, [filterinput]);
  return (
    <div style={{ minHeight: "100vh" }} className="bg-black w-100  p-0 m-0 ">
      <Head>
        <title>World Parrots || Gallery</title>
        <meta name="description" content="Generated by World Parrots" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="w-100 p-0 px-4 px-  container-lg">
        <div className="w-100 p-0 m-0">
          <img
            style={{ height: "200px", objectFit: "cover" }}
            src="https://cheetez.net/gallery/img/Header.png"
            className="w-100"
          />
        </div>
        <div className="py-4 w-100 p-0 m-0 row">
          <div className="col-md-3 p-0 m-0">
            <div
              style={{ boxShadow: "0 2px 12px 0 hsla(0,0%,100%,.25)" }}
              className="w-100 p-0 m-0 p-3 rounded bg-dark border border-light"
            >
              <div
                style={{ color: "gold", fontFamily: "cursive" }}
                className="w-100 fs-5 p-0 m-0"
              >
                Filters Ranking
              </div>
              <div className="w-100 p-0 m-0 py-2">
                <input
                  type="text"
                  className="mt-3 p-2 bg-white rounded  w-100 text-dark form-control "
                  placeholder="Search by ID"
                  onChange={(e) => setFilterinput(e.target.value)}
                />
              </div>
            </div>
          </div>
          <div className="col-md-9 row p-0 m-0 px-lg-3 py-3 py-lg-0">
            {filterinput
              ? parrotInformation.map((e) => {
                  if (filterinput == e.id) {
                    return (
                      <div className="col-sm-6 col-lg-4 col-xl-3 p-2">
                        <img src={e.src} className="w-100 p-0 m-0" />
                        <div className="border border-dark rounded-bottom w-100 m-0 text-white">
                          <div className="w-100 p-0 m-0 p-3 border-bottom border-dark d-flex justify-content-between">
                            <span>#{e.id}</span>
                          </div>
                          <div className="w-100 p-0 m-0 p-3  text-center">
                            Parrot Collection
                          </div>
                        </div>
                      </div>
                    );
                  }
                })
              : parrotInformation.map((e) => {
                  return (
                    <div className="col-sm-6 col-lg-4 col-xl-3 p-2">
                      <img src={e.src} className="w-100 p-0 m-0" />
                      <div className="border border-dark rounded-bottom w-100 m-0 text-white">
                        <div className="w-100 p-0 m-0 p-3 border-bottom border-dark d-flex justify-content-between">
                          <span>#{e.id}</span>
                        </div>
                        <div className="w-100 p-0 m-0 p-3  text-center">
                          Parrot Collection
                        </div>
                      </div>
                    </div>
                  );
                })}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Gallery;
